port="8888"
dev = true


[data_base]
db_host="localhost"
db_port="3306"
db_schema_name="swan_scan"
db_username="root"
db_pwd="123456"
db_args="charset=utf8mb4&parseTime=True&loc=Local"

[nbai_mainnet_node]
rpc_url = ""
payment_contract_address = ""
contract_function_signature = ""
scan_step = 2000
start_from_blockNo = 7005254
cycle_time_interval = 10 #unit:second


[bsc_mainnet_node]
rpc_url = "https://data-seed-prebsc-1-s1.binance.org:8545/"
#rpc_url = "https://bsc-dataseed.binance.org/"
bsc_admin_wallet = ""
#bscAdminWallet = ""
child_chain_manage_contract_address = ""
gas_limit = 800000
chain_ID = 97  # mainnet 56 ;test net 97


[schedule_rule]
nbai2bsc_mapping_redoRule = "0 */3 * * * ?"  #every minute
